version: '3.9'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sellphone-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgredb
    env_file:
      - .env

  postgredb:
    image: postgres:15
    container_name: postgredb
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgredb:/var/lib/postgresql/data

volumes:
  postgredb:
    name: sellphone-postgredb